# Generated by Django 6.0 on 2026-01-12 04:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('date_up', models.DateTimeField(auto_now_add=True)),
                ('date_sign', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='So dien thoai cua hang')),
                ('email', models.CharField(max_length=255, verbose_name='Email cua hang')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Toa do')),
                ('state', models.CharField(max_length=50, verbose_name='Trang thai cua hang')),
                ('describe', models.TextField(blank=True)),
                ('open_time', models.TimeField(verbose_name='Gio mo cua')),
                ('close_time', models.TimeField(verbose_name='Gio dong cua')),
                ('rating_avg', models.FloatField(default=0.0, verbose_name='Diem danh gia trung binh')),
                ('rating_count', models.IntegerField(default=0, verbose_name='So luot danh gia')),
            ],
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(blank=True)),
                ('state', models.CharField(max_length=50)),
                ('time_up', models.TimeField(verbose_name='Thoi gian chup')),
            ],
        ),
    ]
