# Generated by Django 6.0 on 2026-01-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='Hinh anh'),
        ),
    ]
