# Generated by Django 6.0 on 2026-01-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_storeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='time_up',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
