# Generated by Django 6.0 on 2026-01-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_storeimage_time_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20),
        ),
    ]
