# Generated by Django 6.0 on 2026-01-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_approvalprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(default='private', max_length=50),
        ),
    ]
