# Generated by Django 6.0 on 2026-01-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_store_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(max_length=50, verbose_name='Trang thai cua hang'),
        ),
    ]
