# Generated by Django 6.0 on 2026-01-27 02:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_store_is_active_alter_store_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='close_time',
            field=models.TimeField(verbose_name='Closing Time'),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Store Email'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='store',
            name='open_time',
            field=models.TimeField(verbose_name='Opening Time'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Store Phone Number'),
        ),
        migrations.AlterField(
            model_name='store',
            name='rating_avg',
            field=models.FloatField(default=0.0, verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='store',
            name='rating_count',
            field=models.IntegerField(default=0, verbose_name='Review Count'),
        ),
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(max_length=50, verbose_name='Store Status'),
        ),
        migrations.AlterField(
            model_name='storeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='Image'),
        ),
    ]
