# Generated by Django 6.0 on 2026-02-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_alter_category_options_category_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
