# Generated by Django 6.0 on 2026-02-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_alter_category_options_remove_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='dummy_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/', verbose_name='System Trigger (Ignore)'),
        ),
    ]
