# Generated by Django 6.0 on 2026-02-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_store_dummy_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='trigger_upload',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
    ]
