# Generated by Django 6.0 on 2026-02-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_store_trigger_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimage',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='shops.store'),
        ),
    ]
