# Generated by Django 6.0 on 2026-02-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_alter_storeimage_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='dummy_file',
        ),
        migrations.RemoveField(
            model_name='store',
            name='trigger_upload',
        ),
    ]
