# Generated by Django 6.0 on 2026-02-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_remove_store_dummy_file_remove_store_trigger_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Category Icon'),
        ),
    ]
