# Generated by Django 6.0 on 2026-03-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Closing Time'),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Store Email'),
        ),
        migrations.AlterField(
            model_name='store',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Opening Time'),
        ),
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50, verbose_name='Store Status'),
        ),
    ]
