# Generated by Django 6.0 on 2026-04-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_alter_store_close_time_alter_store_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, help_text="Nhiều số điện thoại ngăn cách bằng ' | ', VD: 0901234567 | 0281234567", max_length=100, null=True, verbose_name='Store Phone Number'),
        ),
    ]
