# Generated by Django 6.0 on 2026-04-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0017_phone_max_length_100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_active',
        ),
    ]
