# Generated by Django 6.0 on 2026-04-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_remove_store_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
